### PR TITLE
Modify rogue file collection to always include firmware/python directory

### PR DESCRIPTION
**Pull request by slacrherbst**

### CODE REVIEW

**Comment by ruck314** [comment]
@slacrherbst: Can you explain why you need this modification and how Line#33-51 operation does not do what you need?
https://github.com/slaclab/ruckus/blob/v1.8.1/vivado_pyrogue.tcl#L33-L51

**Comment by slacrherbst** [comment]
I did not think the firmware/ sub-directory would normally be part of the ruckus dir list as it does not have its own ruckus.tcl file and is not included in the list of directories containing firmware to be included.

**Comment by slacrherbst** [comment]
The approach going forward as we decouple the python/cpsw release from the build process will be to no longer include python sub-dirs in every firmware sub-dir, instead include them in the sub-module top levels as well as firmware/python.

**Comment by ruck314** [comment]
Ok, that makes sense now.  
Do you need to do the same procedure in vivado_cpsw.tcl as well?

**Comment by slacrherbst** [comment]
I am not sure if we want to modify cpsw at this time, but maybe for constancy?

**Comment by ruck314** [comment]
Let’s hold off on touching anything CPSW related in ruckus for now

**Pull request merged**
