### PR TITLE
ESCORE-304

### PR DESCRIPTION
**Pull request by ruck314**
Including the defaults config folder into either the pyrogue.tar.gz or cpsw.tar.gz

### CODE REVIEW

**Comment by ernestow** [comment]
Hi Larry,


Awesome.


Thanks for supporting this one.  👍


Till and Jesus can you test this?




Cheers,


Ernest Williams
Dept. Head, Advanced Control Systems
Advanced Instrumentation Research, Technology Innovation Directorate
SLAC National Laboratory, Stanford University


________________________________

**Comment by till-s** [comment]
I think this solution is acceptable. Hopefully users will not get confused by the register-definition and defaults files residing under a common directory...

**Comment by ernestow** [comment]
Hi Till and Larry,


That will be confusing.


Please create a sub directory and name it for example:


"default-config"  or "default_config"




Cheers,


Ernest Williams
Dept. Head, Advanced Control Systems
Advanced Instrumentation Research, Technology Innovation Directorate
SLAC National Laboratory, Stanford University


________________________________

**Comment by till-s** [comment]
The way it is now, the tarball contains a top directory with all the register-definition .yaml files. Inside the top directory there is a config/ subdirectory with the default yaml file(s).

**Comment by ernestow** [comment]
Okay, as long it contains a subdirectory it is good.





Cheers,



Ernest Williams
Dept. Head, Advanced Control Systems
Advanced Instrumentation Research, Technology Innovation Directorate
SLAC National Laboratory, Stanford University


________________________________

**Pull request merged**
