### PR TITLE
Support central scripts for release notes and release generation

### PR DESCRIPTION
**Pull request by slacrherbst**
This moves two scripts to the scripts directory in ruckus. These scripts can be used to generate a release in response to a created tag. I have tested this with rogue.

https://github.com/slaclab/rogue/blob/8d3f48570395071fc61e4183ee8acfd87217f0c6/.travis.yml#L126-L132

### CODE REVIEW

**Comment by slacrherbst** [comment]
Hmm. I wonder if pip_requirements should be in ruckus ?

**Comment by ruck314** [comment]
There are two releaseGen scripts. One in “ scripts/releaseGen.py” and one in “releaseGen.py”. I think you want to get rid of “releaseGen.py”.

**Comment by slacrherbst** [comment]
the releaseGen in the base directory is the script which is still used for the firmware release. I was going to rename it and move it to scripts as a second step, but I think this PR breaks it. So I will move that as well.

**Comment by ruck314** [comment]
I agree the pip install will be required for all the python lib dependency (e.g. import github)

**Comment by slacrherbst** [comment]
I renamed the old releaseGen script to scripts/firmwareRelease.py. I also added a pip_requirements file that can be used to load script requirements. Example usage:

https://github.com/slaclab/rogue/blob/b9a4fe42ef9f180f4d066fab10f9b39e4ab5b5c9/.travis.yml#L126-L132

**Pull request merged**
