### PR TITLE
Added ModelSim/Questa simulation support

### PR DESCRIPTION
**Pull request by FilMarini**
Hi Larry,
I've been using ruckus for projects I've been working on (its great! Thanks for developing it), and I added support for Vivado simulation using either ModelSim or Questa.

The msim.tcl script automatically detect whether you're using ModelSim or Questa (based on either what you have on your PATH or by explicitly using an environmental variable, MSIM_PATH), and whether you need to compile or not simulation libraries and then starts the simulation (its different compared to the VCS tcl script, since here no scripts are generated, but works more like the XSim tcl script).

The only thing Im not able to figure out is an error compiling the simulation libraries. If I run the `compile_simlib` in the  "ruckus environment" I get errors, but if I ran the identical command on a separate instance of vivado in tcl mode, the command is successful..
Do you have any idea why this could happen?

### CODE REVIEW

**Comment by FilMarini** [comment]
It seems like the issue in the simulation libraries compilation is caused by `export LD_PRELOAD =` in the system_vivado.mk file (Here: https://github.com/slaclab/ruckus/blob/main/system_vivado.mk#L155)

If I comment out that line then the libraries are compiled correctly from the msim.tcl script.

**Comment by ruck314** [comment]
@FilMarini Looks like LD_LOAD was added for SDK (which got later replaced by Vitis): https://github.com/slaclab/ruckus/commit/f55b97486aa6ffb06d3e66e0de600b15a21ccca1

I am going to do some regression testing with Vitis integrated into Vivado build.tcl to determine if we can remove the LD_LOAD env var

**Comment by ruck314** [comment]
@FilMarini I think PR #276 will resolve your issue while handling backwards compatibility with older versions of Vivado. Let me know when you are ready for me to merge your branch in this PR.

**Review by ruck314 — APPROVED** [review]

**Comment by FilMarini** [comment]
Hi Larry,
I've tested PR #276 and the simulation libraries compile correctly.
From my side the PR is ready to be merged.
Thanks!

**Pull request merged**
