### PR TITLE
Dev vivado sim

### PR DESCRIPTION
**Pull request by RobertGlein**
Hi Larry,
I am working with Aleš and we both use your great CLI build tool.
I added the feature of the Vivado simulation and I think it will be a benefit for the tool.

One thing I am not sure about is the BuildIpCores function which I use in the vivado_sim.tcl file. It builds the IP cores but for the simulation export_ip_user_files would be enough. I do not think it is a big deal because the IP cores have to be build anyways but it takes more time for the first simulation. What do you think?

Best,
Robért

### CODE REVIEW

**Comment by ruck314** [comment]
```simulation export_ip_user_files would be enough```
Try this:
https://github.com/slaclab/ruckus/blob/master/vivado_vcs.tcl#L166-L168

**Comment by ruck314** [comment]
@RobertGlein: Does ca2fea4 fix your issue for the long time to build the IP cores before running your XSIM?

**Comment by RobertGlein** [comment]
@ruck314: Yes it works just fine now. I also ran my CI pipelines to successfully verify the change. 
Thank you for your help.

**Comment by ruck314** [comment]
@RobertGlein: Out of curiosity, are you running "Travis CI" for your CI platform? Or on a local server?

**Comment by RobertGlein** [comment]
@ruck314: We are using GitLab CI hosted by CERN which is supposed to be one of the best CIs: https://about.gitlab.com/devops-tools/ 
This triggers the runs of jobs on local workstations with the Vivado tools installed

**Pull request merged**
